---
- name: promote windows server
  hosts: dc
  gather_facts: true
  vars_files:
    - ../../vars/main.yml

  tasks: 
    - name: install adds
      win_feature:
        name: AD-Domain-Services
        state: present
        include_sub_features: true
        include_management_tools: true
      register: adds_install

    - name: configure ad
      microsoft.ad.domain:
        dns_domain_name: "{{ domain_name }}"
        safe_mode_password: "{{ domain_admin_password }}"
      register: ad_setup
      when: adds_install.changed

    - name: reboot after installation
      win_reboot:
        reboot_timeout: 3700
      when: ad_setup.changed 

    - name: weaken domain password policy
      win_shell: |
        Set-ADDefaultDomainPasswordPolicy -Identity {{ domain_name }} -ComplexityEnabled $false -MinPasswordLength 4 -PasswordHistoryCount 1 

    - name: create groups (high privilege)
      microsoft.ad.group:
        name: "{{ item }}"
        scope: global
      loop: "{{ high_groups }}"

    - name: create groups (mid privilege)
      microsoft.ad.group:
        name: "{{ item }}"
        scope: global
      loop: "{{ mid_groups }}"

    - name: create groups (normal privilege)
      microsoft.ad.group:
        name: "{{ item }}"
        scope: global
      loop: "{{ normal_groups }}"

    - name: create service accounts
      microsoft.ad.user:
        name: "{{ item }}"
        password: service_accounts.mssql_svc.password
        password_never_expires: yes
        spn:
          add:
            - "{{ service_accounts[item].spn }}/{{ ansible_host }}"
        state: present
      loop: "{{ service_accounts.keys() | list }}"

    - name: configure users for asrep roast
      microsoft.ad.user:
        name: "{{ item }}"
        password: "ChangeMe123!"
        state: present
      loop: "{{ asrep_users }}"

    - name: disable kerberos preauth
      win_shell: |
        Set-ADAccountControl -Identity {{ item }} -DoesNotRequirePreAuth $true
      loop: "{{ asrep_users }}"

    - name: add users to dns admins group
      win_shell: |
        Add-ADGroupMember -Identity "DnsAdmins" -Members "Senior Management"
    
    - name: disable smb signing
      win_shell: |
        Set-SmbClientConfiguration -RequireSecuritySignature 0 -EnableSecuritySignature 0 -Confirm:$false -Force
