---
- name: DC - PROMOTE WINDOWS SERVER
  hosts: dc
  gather_facts: true
  vars_files:
    - ../../vars/main.yml

  tasks:
    - name: install adds
      win_feature:
        name: AD-Domain-Services
        state: present
        include_sub_features: true
        include_management_tools: true
      register: adds_install

    - name: reboot after feature installation if needed
      win_reboot:
        reboot_timeout: 3600
      when: adds_install.reboot_required is defined and adds_install.reboot_required

    - name: check if domain already exists
      win_shell: |
        try {
            Get-ADDomain -ErrorAction Stop
            Write-Output "domain_exists"
        } catch {
            Write-Output "domain_not_exists"
        }
      register: domain_check

    - name: create new ad forest and domain
      microsoft.ad.domain:
        dns_domain_name: "{{ domain_name }}"
        safe_mode_password: "{{ domain_admin_password }}"
        reboot: true 
      register: ad_setup
      when: "'domain_not_exists' in domain_check.stdout"
