---
- name: Configure Primary Windows Domain Controller
  hosts: windows
  gather_facts: yes
  tasks:
    - name: Install AD DS feature
      win_feature:
        name: AD-Domain-Services
        state: present
        include_sub_features: yes
        include_management_tools: yes
      register: ad_install

    - name: Reboot if required
      win_reboot:
        msg: "[INFO] Rebooting to complete AD DS installation"
      when: ad_install.reboot_required

    - name: Configure Windows Domain
      win_domain:
        dns_domain_name: "{{ dc_info['domain_name'] }}"
        safe_mode_password: "{{ dc_info['safemode_pw'] }}"
      register: domain_config

    - name: Reboot after domain creation
      win_reboot:
        msg: "[INFO] Rebooting to complete domain creation"
      when: domain_config.reboot_required

    - name: Promote server to Domain Controller
      win_domain_controller:
        dns_domain_name: "{{ dc_info['domain_name'] }}"
        domain_admin_user: "{{ dc_info['admin_user'] }}"
        domain_admin_password: "{{ dc_info['admin_pw'] }}"
        safe_mode_password: "{{ dc_info['safemode_pw'] }}"
        state: "{{ dc_info['state'] }}"
      register: dc_promotion

    - name: Final reboot if required
      win_reboot:
        msg: "[INFO] Rebooting to complete DC promotion"
      when: dc_promotion.reboot_required
