instance_type = "t2.micro"
region        = "eu-central-1"
ssh_username  = "admin"
keypair_name  = "ed"
key_file      = "ed.pem"
ami_name      = "ED-ATK-{{timestamp}}"
source_ami    = "ami-0ef32de3e8ab0640e"
