---
- name: VULN - GROUP NESTING
  hosts: dc
  gather_facts: false
  vars_files:
    - ../../vars/main.yml
  vars:
    vuln_group: "IT Service"

  tasks:
    - name: add it service to domain admins
      win_shell: |
        Add-ADGroupMember -Identity "Domain Admins" -Members "{{ vuln_group }}"
