---
- name: VULN - SMB SIGNING DISABLED
  hosts: dc
  gather_facts: false

  tasks:
    - name: disable SMB signing via registry (server)
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters
        name: RequireSecuritySignature
        data: 0
        type: dword

    - name: disable SMB signing via registry (workstation)
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\LanmanWorkstation\Parameters
        name: RequireSecuritySignature
        data: 0
        type: dword
