---
- name: VULN - WEAK OU ACL
  hosts: dc
  gather_facts: false
  vars_files:
    - ../../vars/main.yml
  vars:
    vuln_group: "IT Service"
    ou_dn: "OU=Workstations,DC=issp,DC=local"

  tasks:
    - name: grant genericall to group on ou
      win_shell: |
        $sid = (Get-ADGroup "{{ vuln_group }}").SID
        dsacls "{{ ou_dn }}" /G "${sid}:GA"
