---
- import_playbook: ../roles/dc/jet.yml
- import_playbook: ../roles/ad/ous.yml 
- import_playbook: ../roles/ad/users.yml
- import_playbook: ../roles/ad/groups.yml
- import_playbook: ../roles/ad/computers.yml
- import_playbook: ../challenges/constrained-delegation/main.yml
- import_playbook: ../challenges/unconstrained-delegation/main.yml
- import_playbook: ../challenges/group-nesting/main.yml
- import_playbook: ../challenges/asreproast/main.yml
- import_playbook: ../challenges/pwd-policy/main.yml
- import_playbook: ../challenges/kerberoast/main.yml
- import_playbook: ../challenges/smb-signin/gmain.yml
- import_playbook: ../challenges/smb-share/main.yml

