---
- name: create ad vulnerabilities
  hosts: dc
  gather_facts: yes
  vars_files:
    - ../vars/main.yml

  tasks:
    - name: weaken domain password policy
      win_shell: |
        Set-ADDefaultDomainPasswordPolicy -Identity {{ domain_name }} -ComplexityEnabled $False -MinPasswordLength 4 -PasswordHistoryCount 1
      register: pwpolicy

    - name: show password policies
      debug:
        var: pwpolicy.stdout_lines
      when: pwpolicy.stdout_lines is defined
    
    - name: create groups (high privilege)
      microsoft.ad.group:
        name: "{{ item }}"
        scope: global
      loop: "{{ high_groups }}"

    - name: create groups (mid privilege)
      microsoft.ad.group:
        name: "{{ item }}"
        scope: global
      loop: "{{ mid_groups }}"

    - name: create groups (normal privilege)
      microsoft.ad.group:
        name: "{{ item }}"
        scope: global
      loop: "{{ normal_groups }}"

    - name: create service accounts
      microsoft.ad.user:
        name: "{{ item.key }}"
        spn: "{{ item.value.password | default('WeakPassword123!) }}"
        password_never_expires: yes
      loop: "{{ service_accounts | dict2items }}"

    - name: configure users for asrep roast
      microsoft.ad.user:
        name: "{{ item }}"
        password: "ChangeMe123!"
        state: present
      loop: "{{ asrep_user }}"

    - name: disable kerberos preauth
      win_shell: |
        Set-ADUser -Identity "{{ item }}" -DoesNotRequirePreAuth $true
      loop: "{{ asrep_users }}"

    - name: add users to dns admins group
      win_shell: |
        Add-ADGroupMember -Identity "DnsAdmins" -Members "{{ mid_groups[0] }}"

    - name: disable smb signing
      win_shell: |
        Set-SmbClientConfiguration -RequireSecuritySignature 0 -EnableSecuritySignature 0 -Confirm:$false -Force
