---
- name: computer accounts
  hosts: dc
  gather_facts: true
  vars_files:
    - ../../vars/main.yml

  tasks:
    - name: Create computers
      microsoft.ad.computer:
        name: "{{ item.name }}"
        path: "{{ item.ou }}"
        state: present
      loop: "{{ ad_computers }}"
