---
- name: AD - ORGANIZATIONAL UNITS
  hosts: dc
  gather_facts: true
  vars_files:
    - ../../vars/main.yml
  
  tasks:
    - name: create ous
      microsoft.ad.ou:
        name: "{{ item }}"
        state: present
      loop: "{{ ad_ous }}"
